### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by martinjoiner** [carbonvisuals/eve#3]
- [ ] API routes
 - [ ] API validates request parameters and returns helpful responses
 - [ ] API authenticates requests based on key
 - [ ] API returns web page containing basic test visualisation on canvas
 - [ ] API renders visualisation server-side and returns still image file
